"""empty message

Revision ID: 9f462f703916
Revises: f937f15c009d
Create Date: 2021-04-23 01:44:45.672645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f462f703916'
down_revision = 'f937f15c009d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advert_timestamp'), 'advert', ['timestamp'], unique=False)
    op.create_index(op.f('ix_advert_title'), 'advert', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advert_title'), table_name='advert')
    op.drop_index(op.f('ix_advert_timestamp'), table_name='advert')
    op.drop_table('advert')
    # ### end Alembic commands ###
